### ISSUE TITLE
headless analysis script error

### ISSUE THREAD

**Issue by Ruturaj4** [GrammaTech/retypd-ghidra-plugin#1]
The script gives me following error:

```
 (AutoAnalysisManager)  
INFO  REPORT: Analysis succeeded for file: /small_examples/benchmarks/stripped/test.exe (HeadlessAnalyzer)  
INFO  SCRIPT: 
/open_source/ghidra_10.2.3_PUBLIC/Ghidra/Extensions/GhidraRetypd/ghidra_scripts/Retypd.java (HeadlessAnalyzer)  
WARN  Decompiling 00204020, pcode error at 00204020: Unable to disassemble EXTERNAL block location: 00204020 (DecompileCallback)  
WARN  Decompiling 00204008, pcode error at 00204008: Unable to disassemble EXTERNAL block location: 00204008 (DecompileCallback)  
WARN  Decompiling 00204000, pcode error at 00204000: Unable to disassemble EXTERNAL block location: 00204000 (DecompileCallback)  
INFO  Executing command: retypd-ghidra --json-in /tmp/retypd3995791693830618628/bin.json (RetypdRunner)  
INFO  Retypd.java> ERROR:  Failed to execute Retypd executable: ghidraretypd.AnalysisException: Failed to execute ghidra-retypd:
Traceback (most recent call last):
  File "/open_source/retypd-ghidra-plugin/ghidra_retypd_provider/venv/bin/retypd-ghidra", line 33, in <module>
    sys.exit(load_entry_point('ghidra-retypd-provider==0.1.dev0', 'console_scripts', 'retypd-ghidra')())
  File "/pcfi/open_source/retypd-ghidra-plugin/ghidra_retypd_provider/venv/lib64/python3.9/site-packages/ghidra_retypd_provider/main.py", line 47, in main
    types = infer_types(args.json_in, args.function)
  File "/pcfi/open_source/retypd-ghidra-plugin/ghidra_retypd_provider/venv/lib64/python3.9/site-packages/ghidra_retypd_provider/type_inference.py", line 112, in infer_types
    config = SolverConfig(
TypeError: __init__() got an unexpected keyword argument 'max_path_length' (GhidraScript)  
Writing JSON output to /tmp/retypd3995791693830618628/bin.json
```

The error comes when `SolverConfig` tries to behave like `GraphSolverConfig`.

Edit:

I made following change to type_inference.py
```
config = SolverConfig(graph_solver_config = GraphSolverConfig(
        max_path_length=15,
        max_paths_per_root=5000,
        max_total_paths=100000,
        # precise_globals=False,
        restrict_graph_to_reachable = False
    ))
```

And now it works, but I am not sure if that's the best way.

**Comment by aeflores** [comment]
hi @Ruturaj4, thanks for your interest in Retypd. There was a problem with our mirroring which caused a mismatch between the `retypd` and `retypd-ghidra-plugin` versions. I have now updated retypd-ghidra-plugin and the problem that you observed should be solved.

Please reopen if you still have problems.
